### ISSUE TITLE
Inject to Process?

### ISSUE THREAD

**Issue by Talithaald** [dretax/DynamicDllLoader#1]
Hello Dretax!

I've been learning c# for 1month, and i'm currently making a csgo loader. 
When i run the program, i've placed the .dll inside of the same folder with the .exe file, it says Loaded : True,
but how do we inject that loaded byte?

Thank you!
love your repos by the way ( i;m still learning, and hoping to learn alot from you ) ^^b

**Comment by dretax** [comment]
Howdy.

This repository is specialized to use a byte array when loading a dll in a similar way as LoadLibrary does.

What DLL are you trying to load?
The dll that you are injecting must be a C++ DLL.

**Comment by Talithaald** [comment]
Yes, the .dll is indeed a c++ .dll compiled from Visual Studio

**Comment by Talithaald** [comment]
The .dll is loaded, but how do i inject that loaded dll byte into a process? since i do not see any "inject to process" on the source code ( correct me if i'm wrong ).

Thanks!

**Comment by dretax** [comment]
Ahh.

This source allows you to process C++ dlls that are loaded using C# code. It was not made to inject into external processes. However
you may change the internal unsafe bool LoadLibrary(byte[] data)
to work in a way that injects into a specific process.

Have you ever made a code that does native injection using C#?
You basically call the native functions that are implemented in the windows dlls.

`
        const int PROCESS_CREATE_THREAD = 0x0002;
        const int PROCESS_QUERY_INFORMATION = 0x0400;
        const int PROCESS_VM_OPERATION = 0x0008;
        const int PROCESS_VM_WRITE = 0x0020;
        const int PROCESS_VM_READ = 0x0010;

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern IntPtr OpenProcess(uint dwDesiredAccess, int bInheritHandle, uint dwProcessId);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern int CloseHandle(IntPtr hObject);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern IntPtr GetProcAddress(IntPtr hModule, string lpProcName);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern IntPtr GetModuleHandle(string lpModuleName);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern IntPtr VirtualAllocEx(IntPtr hProcess, IntPtr lpAddress, IntPtr dwSize,
            uint flAllocationType,
            uint flProtect);
        
        [DllImport("kernel32.dll")]
        private static extern bool ReadProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, int dwSize, ref int lpNumberOfBytesRead);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern int WriteProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] buffer, uint size,
            int lpNumberOfBytesWritten);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern IntPtr CreateRemoteThread(IntPtr hProcess, IntPtr lpThreadAttribute, IntPtr dwStackSize,
            IntPtr lpStartAddress,
            IntPtr lpParameter, uint dwCreationFlags, IntPtr lpThreadId);
        

        internal static bool DoNativeInjection(int TargetProcess, string DllName)
        {
            IntPtr processhandle = OpenProcess((PROCESS_CREATE_THREAD | PROCESS_QUERY_INFORMATION | PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_VM_READ), 1, (uint) TargetProcess);
            if (processhandle == IntPtr.Zero)
            {
                return false;
            }

            IntPtr LoadLibrary = GetProcAddress(GetModuleHandle("kernel32.dll"), "LoadLibraryA");
            if (LoadLibrary == IntPtr.Zero)
            {
                return false;
            }

            IntPtr address =
                VirtualAllocEx(processhandle, (IntPtr) null, (IntPtr) DllName.Length, (0x1000 | 0x2000), 0X40);
            if (address == IntPtr.Zero)
            {
                return false;
            }

            byte[] bytes = Encoding.ASCII.GetBytes(DllName);
            if (WriteProcessMemory(processhandle, address, bytes, (uint) bytes.Length, 0) == 0)
            {
                return false;
            }

            if (CreateRemoteThread(processhandle, (IntPtr) null, IntPtr.Zero,
                LoadLibrary, address, 0, (IntPtr) null) == IntPtr.Zero)
            {
                return false;
            }
            
            int bytesRead = 0;
            byte[] buffer = new byte[24];
            ReadProcessMemory(processhandle, address, buffer, buffer.Length, ref bytesRead);
            Console.WriteLine("Data in memory: " + System.Text.Encoding.UTF8.GetString(buffer));


            CloseHandle(processhandle);
            return true;
        }
`

If you experienced how to do native injection, I'd recommend you to take a look at injectors and try to understand how they manual map their dlls in processes. Lately VAC hooked LoadLibrary, therefore It is detected.

**Comment by Talithaald** [comment]
Thank you for the response, it'll help me learn much! 
with the Injection method above, is it almost the same as Putting the .dll in the harddisk then injecting it?

looking forward for your reply,
Thank you!

**Comment by dretax** [comment]
Yes. The target dll can be placed in the directory where the exe is running. 
You get a target process and the dll name and the native injection is complete.

**Comment by Talithaald** [comment]
so with this Native Injection method, it's possible to delete the .dll file because the "binary" that gets injected into a process is already stored in the memory?

Thanks again :D

**Comment by dretax** [comment]
Yes, we already have a byte array which is in the memory. Then It also offers the possibility to iterate through the native functions, and work with them, etc.

**Comment by Talithaald** [comment]
ah big thanks, i'll try to explore with the code you gave me ^^

**Comment by Talithaald** [comment]
Hello Dretax ^^ thank you for the huge help, it opened my eyes towards alot of new stuffs to learn :D, is it possible for me to ask for another question tho? I searched everywhere but i think my Keyword is just wrong, so maybe if you know what i meant it'll be easier for me to Google ^^

I'm learning to inject hexcode into a dll with ManualMapping.

`
byte[] hexd = { 0x4d, 0x5a, 0x80, 0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x10, 0x00, 0xff, 0xff, 0x00, 0x00, };
`
`
var injector = new ManualMapInjector(target) { AsyncInjection = true };
`
`
Console.WriteLine($"hmodule = 0x{injector.Inject(hexd).ToInt64():x8}");
`
Lets say byte[] hexd = { xxx } is a hex code of a .dll,
The code above will definitely work, but it's not easy to maintain ( as if we're going update the .dll file continuesly )
is it possible to port it into something like this?
`
byte[] hexd = { webClient.DownloadString(url) };
`
The web response from the url will return this:
`
0x4d, 0x5a, 0x80, 0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x10, 0x00, 0xff, 0xff, 0x00, 0x00, 
`
So it's similar with 
`
byte[] hexd = { 0x4d, 0x5a, 0x80, 0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x10, 0x00, 0xff, 0xff, 0x00, 0x00, };
`

so if i were to execute this
`
byte[] hexd = { webClient.DownloadString(url) };
`
instead of
`
byte[] hexd = { 0x4d, 0x5a, 0x80, 0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x10, 0x00, 0xff, 0xff, 0x00, 0x00, };
`
what do you think i should do to make it work? :D
i tried and it didn't work sadly

Thank you!

**Comment by dretax** [comment]
Add me on discord.
DreTaX#3519

**Comment by Talithaald** [comment]
added :D thank you
